name: 'upLaTeX Action'
description: 'GitHub Action to compile LaTeX documents with upLaTeX'
inputs:
  target_file:
    description: 'The LaTeX file to be compiled'
    required: true
  working_directory:
    description: 'The working directory for LaTeX engine'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target_file }}
    - ${{ inputs.working_directory }}
