name: Test Github Action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile basic LaTeX document
        uses: ./
        with:
          target_file: test.tex
          working_directory: test/
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: test
          path: test
        if: always()
